---
- name: 
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
  roles:
    - pandaUsers
    - packages
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform